---
- name: Selenoid-UI | Check selenoid container exist
  shell: 'docker ps -aq --filter "name={{ item }}"'
  with_items:
    - 'selenoid-ui'
  register: found_ui_containers

- name: Selenoid-UI | Remove selenoid-ui container if exist
  shell: 'docker stop {{ item.item }} && docker rm -fv {{ item.item }}'
  with_items: '{{ found_ui_containers.results }}'
  when: item.stdout
