---
- name: Setup influxDb
  gather_facts: no
  hosts: influxdb
  vars:
    - influxdb_port: 8086
  roles:
    - influxdb

- name: Setup selenoid and telegraf
  hosts: selenoid-node
  roles:
    - selenoid
  vars:
    - telegraf: true
    - selenoid_url: "http://selenoid-node.mydev.com"
    - influxdb_url: "http://selenoid-ui.mydev.com"
    - influxdb_port: 8086
    - selenoid_browsers:
      - name: "chrome"
        default: "74.0"
        versions:
          - "74.0"
      - name: "firefox"
        default:  "67.0"
        versions:
          - "67.0"

- name: Setup selenoid-ui
  gather_facts: no
  hosts: selenoid-ui
  vars:
    - selenoid_url: "http://selenoid-ui.mydev.com"
    - selenoid_ui_port: 8081
  roles:
    - selenoid-ui
